version: "3.7"

services:
  nginx:
      image: nginx:latest
      container_name: edocker-nextjs-nginx-3
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 84:80
        - 448:443

  dev:

    build:
      context: .
      dockerfile: Dockerfile
    container_name: edocker-nextjs-dev-3
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - .:/psychologist-cards
      - /psychologist-cards/node_modules
      - /psychologist-cards/.next
    ports:
      - "3003:3000"
    
volumes:
  node_modules: